services:
  rstudio:
    image: rstudiorenvtidy:4.4.3
    build:
     context: .
     dockerfile: ./docker/Dockerfile
    container_name: scrnaseq-fritsch-et-al-2025
    ports:
      - "50362:8787"
    volumes:
      - type: "bind"
        source: "./config"
        target: "/home/rstudio/.config/rstudio"
      - type: "bind"
        source: "."
        target: "/home/rstudio/project"
      - type: "bind"
        source: "$HOME/.cache"
        target: "/home/rstudio/.cache"
      - type: "bind"
        source: "/home/aabdallah/tank/RProjects/Kashkar"
        target: "/home/rstudio/project/data"
    environment:
      - USERNAME=aabdallah
      - USERID=1000
      - GROUPID=1000
      - USER=rstudio
      - PASSWORD=1rstudio